name: Renovate
on:
  push:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.4
        with:
          # configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
